### ISSUE TITLE
"Cannot read property 'cid' of undefined" after removing a layer created from another layer

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#10542]
**str**

1. add empty map
2. add layer
3. remove layer

![screen shot 2016-11-04 at 10 40 21](https://cloud.githubusercontent.com/assets/36676/20001399/44a6a676-a27c-11e6-9c0d-1a3730960a37.png)

**Comment by alonsogarciapablo** [comment]
Fixed via https://github.com/CartoDB/cartodb.js/pull/1489.

**Comment by saleiva** [comment]
happening again

**Comment by matallo** [comment]
proper **str**:

1. add empty map
2. create a point
3. add layer
4. remove layer

this is still happening, investigating further

**Comment by alonsogarciapablo** [comment]
@matallo thanks for the STR! I've been able to reproduce it now. Taking a look at the PR.
