### ISSUE TITLE
Wrong user flow involving analyses and empty layers

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13478]
### Context

Right now, if you add certain analysis to a layer that doesn't return any data, Builder considers that layer as empty. And, being an empty layer, it disables all the other tabs, but Data. So users are unable to access the Analysis tab to edit or delete said analyses. 

There's a workaround, by accessing them through the Layers list' analysis nodes "shortcuts" but users should be able to access them from both sides.  

![empty](https://user-images.githubusercontent.com/16247628/35678537-07c46e12-0754-11e8-968a-c2d11854b931.gif)

### Steps to Reproduce

1. Apply an analysis in a layer that will filter out all the data in that layer. 
2. Go back to the Layers list.
3. Access the layer again.

### Expected result

In that instance, when an analysis is filtering out all the data, we shouldn't consider the layer as empty, but as a filtered. 

This is an important one @ramiroaznar 

### PR
- Wrong user flow involving analyses and empty layers: https://github.com/CartoDB/cartodb/pull/13489

**Comment by jesusbotella** [comment]
@arianaescobar Should we take the user to the analysis tab when the layer is empty and has any analysis applied? I think we should, right?

**Comment by arianaescobar** [comment]
It shouldn't be a particular new state, it should be the default state with everything enabled.

**Comment by jesusbotella** [comment]
Should we enable Style, Pop-up, and Legends tabs too? That behaviour of disabling these three tabs wasn't modified when we disabled the analysis tab in the empty layer state, it was changed before.

**Comment by arianaescobar** [comment]
Everything has to be enabled. This isn't an empty state, it's a default normal state with inputs from the user on the analysis tab. 

Disabling those tabs was never meant for this instance.

**Comment by jesusbotella** [comment]
@matallo and I have been talking about this, and even though the tabs should be enabled when layer is empty because of an analysis filtering, it requires further action that should be addressed in other issue.

These actions involve Style, Popup and Legend tabs.

In the Style tab, the style shouldn't be reset when the layer is empty to restore the previous state after reverting the filter if the layer geometry and querySchemaModel has the same schema.

In the Popup tab, we shouldn't let the user select any column when the layer is empty.

![screen shot 2018-02-02 at 14 07 07](https://user-images.githubusercontent.com/4319728/35734848-cb3668e0-0822-11e8-96e4-3c2d41473bd0.png)

In the Legends tab, we shouldn't let the user modify the current legend because we don't have the current layer styles, so there won't be any items in the legend.

In order not to block the important fix for more time, what do you think about addressing the thing of the disabled tabs in another issue?

**Comment by jesusbotella** [comment]
@arianaescobar It is now deployed in `ded11`.

**Comment by arianaescobar** [comment]
I don't think we should address it in a separate issue because of interactions like the following two (take a look at how the tabs change all of the sudden in both): 

![gif](https://user-images.githubusercontent.com/16247628/35742075-bfbd9896-0839-11e8-890c-806450dc1d7b.gif)

![gif2](https://user-images.githubusercontent.com/16247628/35742078-c2843d00-0839-11e8-9c30-df92508b7877.gif)

We shouldn't merge it to production like this :(

**Comment by jesusbotella** [comment]
Yes, you are totally right. I am looking at those cases to fix them ASAP.

**Comment by jesusbotella** [comment]
I have just uploaded a new revision to `ded11` staging. The two bugs that @arianaescobar mentioned should be fixed.

The tabs have been enabled when the layer is empty and has any analyses. And the second bug, which was a routing bug, should be resolved as well.

**Comment by ramiroaznar** [comment]
@arianaescobar @jesusbotella I have checked and this is also happening when applying a query that does not show any geometry (for instance not adding `cartodb_id` or `the_geom_webmercator`). That needs to be fixed as well.

**Comment by arianaescobar** [comment]
A few other things... 

We're still showing the layer as if it were an "Empty layer" and it is not. This icon shouldn't appear.

![screen shot 2018-02-05 at 14 30 52](https://user-images.githubusercontent.com/16247628/35807018-bb8b03ae-0a81-11e8-9adc-5bbdc2ce8d03.png)

If we go to the DATA tab, we should this message from the Empty layer state but in this case, it doesn't apply. Users can't even use the Add geometry feature.

![screen shot 2018-02-05 at 14 31 33](https://user-images.githubusercontent.com/16247628/35807063-ddcadc8c-0a81-11e8-9b48-4f337687636e.png)
 
Let's change it do this:

> No data available.
> There are no results for the combination of analyses applied to your data. Try tweaking them.

![screen shot 2018-02-05 at 16 44 33](https://user-images.githubusercontent.com/16247628/35813499-0f21f6b4-0a94-11e8-9a04-faa5d0c6e0db.png)

It might be a good idea to also show this message in all the other tabs –but Analysis–.

**Comment by elenatorro** [comment]
I've already added this message in the "Data" view. 

![captura de pantalla 2018-02-13 a las 14 54 56](https://user-images.githubusercontent.com/3824953/36153239-e33569b0-10cd-11e8-9569-67d931c7fae6.png)


> It might be a good idea to also show this message in all the other tabs –but Analysis–.

Do you mean the same message? Or instead of "No **data** available" write "No **style** available"? (and the same with infowindows and legends) cc @arianaescobar

**Comment by arianaescobar** [comment]
Awesome, Elena! 

The same exact one! Without data, you can't style or add pop-ups nor legends. So that's step 1.

**Comment by elenatorro** [comment]
Got it! Thanks!

**Comment by ramiroaznar** [comment]
Is this issue solved then?

**Comment by matallo** [comment]
backend tests not passing, ASAP they do we're merging

**Comment by ramiroaznar** [comment]
Cool! I thought it was a RT issue, but I see Bravo is taking care of it.

**Comment by ivanmalagon** [comment]
### The layer is empty (no rows in the dataset)
- Only data tab enabled.
- Text: `This layer is empty`
- Warning icon should be visible both in layer list and in layer edition panels.

![image](https://user-images.githubusercontent.com/1078228/36533962-738b2a2e-17c5-11e8-9e7b-8471fdcbe8f4.png)

### The layer is filtered (there are rows but an analysis returns 0 of them)
- Warning icon should NOT be displayed in any place.
- Analysis tab should be accesible.
- Data, Style, Popup and legend should show the following text.

![image](https://user-images.githubusercontent.com/1078228/36534436-d64fe07c-17c6-11e8-97ad-19b9922a32f7.png)

### Layer that needs geocoding
- What text in data tab?
- What tabs are enabled?
- Should we display the warning icon?

![image](https://user-images.githubusercontent.com/1078228/36534917-554a3818-17c8-11e8-89ea-5e744092a31d.png)

**Comment by arianaescobar** [comment]
> What text in data tab?

"There is no geometry in your data.
Apply a Geocode analysis or manually add geometry data to visualize on the map."

> What tabs are enabled?

Only DATA and ANALYSIS. 

> Should we display the warning icon?

Yes, but only inside the layer. 
Tooltip: "Geocode to visualize on the map" 

![screen shot 2018-02-22 at 18 28 48](https://user-images.githubusercontent.com/16247628/36554016-3eb17dba-17fe-11e8-8af4-a911ea11e3d7.png)

**Comment by ivanmalagon** [comment]
🚀 Shipped!
