### ISSUE TITLE
Editor incorrectly removing redis keys?

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#3944]
When opening a map in the editor, without interacting with it, there are some strange redis commands to delete what seems vizjson/embed caches. One is related to the map you have in the editor but there other six command for another three viz ids.

I'm not sure why that is needed, specially the other viz ids commands. Can you track why we need that?

```
1433538154.303994 [0 127.0.0.1:51454] "del" "visualization:3d5ce24a-c907-11e4-b2fc-6476ba93d4f6:vizjson:1:http" "visualization:3d5ce24a-c907-11e4-b2fc-6476ba93d4f6:vizjson:1:https"
1433538154.304339 [0 127.0.0.1:51454] "del" "visualization:3d5ce24a-c907-11e4-b2fc-6476ba93d4f6:embed:https:1" "visualization:3d5ce24a-c907-11e4-b2fc-6476ba93d4f6:embed:http:1"
1433538154.306446 [0 127.0.0.1:51454] "del" "visualization:3da216b2-c907-11e4-b2fc-6476ba93d4f6:vizjson:1:http" "visualization:3da216b2-c907-11e4-b2fc-6476ba93d4f6:vizjson:1:https"
1433538154.306732 [0 127.0.0.1:51454] "del" "visualization:3da216b2-c907-11e4-b2fc-6476ba93d4f6:embed:https:1" "visualization:3da216b2-c907-11e4-b2fc-6476ba93d4f6:embed:http:1"
1433538154.309861 [0 127.0.0.1:51454] "del" "visualization:f0b2b684-ceee-11e4-ab67-6476ba93d4f6:vizjson:1:http" "visualization:f0b2b684-ceee-11e4-ab67-6476ba93d4f6:vizjson:1:https"
1433538154.310114 [0 127.0.0.1:51454] "del" "visualization:f0b2b684-ceee-11e4-ab67-6476ba93d4f6:embed:https:1" "visualization:f0b2b684-ceee-11e4-ab67-6476ba93d4f6:embed:http:1"
1433538154.312394 [0 127.0.0.1:51454] "del" "visualization:e72fd218-0bc5-11e5-a243-6476ba93d4f6:vizjson:1:http" "visualization:e72fd218-0bc5-11e5-a243-6476ba93d4f6:vizjson:1:https"
1433538154.312737 [0 127.0.0.1:51454] "del" "visualization:e72fd218-0bc5-11e5-a243-6476ba93d4f6:embed:https:1" "visualization:e72fd218-0bc5-11e5-a243-6476ba93d4f6:embed:http:1"
```

**Comment by Kartones** [comment]
it might be the related visualizations, but I'll check

**Comment by ethervoid** [comment]
I'm only able to reproduce with the next steps:

* Create map using data library
* At the end of the creation, when the map is shown, there is a massive invalidation of visualizations provoked by a PUT call from the frontend.

Are you getting this invalidations every time you enter the map?

**Comment by Kartones** [comment]
uhmm, maybe now the problem is not so much because:
a) I already released https://github.com/CartoDB/cartodb/issues/4008 so now there's no "invalidate everything" call
b) Maybe frontend fixed that bug?feature? of "touching" the map just entering into its editor page.

Anyway that massive invalidation should be checked, even if only happens at the end of creation

**Comment by ethervoid** [comment]
Yes, I would like to check all the invalidation problems that we may have and before release a partial patch I'd like to know if the problem reported is solved by fix released.

**Comment by ethervoid** [comment]
After checking this issue for a while there is only one "conflictive" point where the cache invalidation of related tables is made and is done this way in purpose so I assume that the main problem was fixed by @Kartones

**Comment by rochoa** [comment]
This is still happening :cry:.

It's happening due to a `PUT /api/v1/maps/:uuid/layers/:uuid`. That's **also updating the associated named map**, which is a bit problematic because named maps changes means associated resources must be invalidated.

**Comment by ethervoid** [comment]
As @javisantana said the PUT issue is related with this #4627

**Comment by rochoa** [comment]
Oh thanks, I wasn't aware of that issue. :smile:

**Comment by ethervoid** [comment]
My bad was in an email and I haven't updated here. Sorry
