### ISSUE TITLE
POSSIBLE_GEOM_NAMES: Duplicate column error when importing geojson

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#5872]
When trying to upload a geojson containing Twitter data it gives a "Duplicate Column (2005)" error.

## Context

The dataset was downloaded from a CartoDB account in geojson format. It contains Twitter data. When trying to upload it, it returns the mentioned error message. It seems that there is a duplicated column name, but it should be renamed automatically.

## Process

1. User downloads dataset from (GeoJSON format)--> https://team.cartodb.com/u/iriberri/tables/marias.twitter_temblor_terremoto_earthquake/public/map?redirected=true
2. User imports dataset on CartoDB account
3. User gets: "Duplicate Column (2005)" error

## Expected result

The file should be imported without problems, as it was previously downloaded from a working visualization.

## Current result

Import fails, generating the following code:
>8ca9fd17-0718-4155-9ff4-8eda539f9ea3

And the following import log 
````Starting import for /tmp/imports/20151006-17315-jeya3e/marias.geojson 2015-10-06 09:32:15 UTC: Unpacking /tmp/imports/20151006-17315-jeya3e/marias.geojson 2015-10-06 09:32:15 UTC: Filename: /tmp/imports/20151006-17315-1gku6hw/marias.geojson Size (bytes): 74867667 true: Importing data from /tmp/imports/20151006-17315-1gku6hw/marias.geojson true: File-based import load true: Detected encoding UTF-8 true: Using database connection with {:adapter=>"postgres", :encoding=>"unicode", :host=>"10.0.128.17", :database=>"cartodb_user_6b304b59-2c86-4d7b-a8a2-dc98a5a35d48_db", :username=>"postgres", :port=>6432, :connect_timeout=>2.5, :user=>"cartodb_user_3c7fc356-47ed-4e56-b8c6-a97f35f84b47"} false: ogr2ogr call: OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=UTF-8 /usr/bin/ogr2ogr2 -f PostgreSQL PG:"host=10.0.128.17 port=6432 user=cartodb_user_3c7fc356-47ed-4e56-b8c6-a97f35f84b47 dbname=cartodb_user_6b304b59-2c86-4d7b-a8a2-dc98a5a35d48_db password=d778024610ff3e34e2458911aaa6c4937eafcc3dcartodb_user_3c7fc356-47ed-4e56-b8c6-a97f35f84b47" -t_srs EPSG:4326 -lco DIM=2 -lco PRECISION=NO /tmp/imports/20151006-17315-1gku6hw/marias.geojson -nln cdb_importer.importer_2058ff546c0d11e5b57b0e98b61680bf -nlt PROMOTE_TO_MULTI true: ogr2ogr output: ERROR 1: ERROR: column "wkb_geometry" specified more than once ERROR 1: CREATE TABLE "cdb_importer"."importer_2058ff546c0d11e5b57b0e98b61680bf" ( ogc_fid SERIAL, PRIMARY KEY (ogc_fid), "id" VARCHAR, "verb" VARCHAR, "link" VARCHAR, "body" VARCHAR, "objecttype" VARCHAR, "postedtime" timestamp with time zone, "favoritescount" INTEGER, "twitter_filter_level" VARCHAR, "twitter_lang" VARCHAR, "retweetcount" INTEGER, "actor_objecttype" VARCHAR, "actor_id" VARCHAR, "actor_link" VARCHAR, "actor_displayname" VARCHAR, "actor_image" VARCHAR, "actor_summary" VARCHAR, "actor_postedtime" timestamp with time zone, "actor_links" VARCHAR, "actor_location" VARCHAR, "actor_utcoffset" VARCHAR, "actor_preferredusername" VARCHAR, "actor_languages" VARCHAR, "actor_twittertimezone" VARCHAR, "actor_friendscount" INTEGER, "actor_followerscount" INTEGER, "actor_listedcount" INTEGER, "actor_statusescount" INTEGER, "actor_verified" BOOLEAN, "generator_displayname" VARCHAR, "generator_link" VARCHAR, "provider_objecttype" VARCHAR, "provider_displayname" VARCHAR, "provider_link" VARCHAR, "inreplyto_link" VARCHAR, "geo" VARCHAR, "twitter_entities" VARCHAR, "object_objecttype" VARCHAR, "object_id" VARCHAR, "object_summary" VARCHAR, "object_postedtime" timestamp with time zone, "object_link" VARCHAR, "location_objecttype" VARCHAR, "location_displayname" VARCHAR, "location_link" VARCHAR, "location_geo" VARCHAR, "location_streetaddress" VARCHAR, "location_name" VARCHAR, "gnip" VARCHAR, "category_name" INTEGER, "category_terms" VARCHAR, "wkb_geometry" VARCHAR, "cartodb_id" INTEGER, "created_at" timestamp with time zone, "updated_at" timestamp with time zone, "wkb_geometry" geometry(MULTIPOINT,4326) ) ERROR: column "wkb_geometry" specified more than once ERROR 1: Unable to write feature 0 from layer OGRGeoJSON. ERROR 1: Terminating translation prematurely after failed translation of layer OGRGeoJSON (use -skipfailures to skip errors) true: ogr2ogr exit code: 256 true: Errored importing data from /tmp/imports/20151006-17315-1gku6hw/marias.geojson: ===LOG END=== true: ---------------------------------------------------- false: ["/home/ubuntu/www/production.cartodb.com/releases/20151006081939/services/importer/lib/importer/loader.rb:296:in `check_for_import_errors'", "/home/ubuntu/www/production.cartodb.com/releases/20151006081939/services/importer/lib/importer/loader.rb:268:in `run_ogr2ogr'", "/home/ubuntu/www/production.cartodb.com/releases/20151006081939/services/importer/lib/importer/loader.rb:63:in `block (2 levels) in run'", "/home/ubuntu/www/production.cartodb.com/releases/20151006081939/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", ````

**Comment by ernesmb** [comment]
@iriberri

**Comment by rafatower** [comment]
@ernesmb I believe this issue is already fixed in the cartodbfy process (cdb postgres extension). Can you please confirm?

**Comment by ernesmb** [comment]
@rafatower I have just tried again and still reproduces on my org. account. 
I am now trying on my personal one

**Comment by rafatower** [comment]
Sorry, I misread the issue. Actually I think it is a problem with guessing on the table. Thanks!

**Comment by rafatower** [comment]
@ernesmb is this still a problem? Carla has been working on related issues so assigning to her in case we need a further look

**Comment by ernesmb** [comment]
Just tried and reproduced the error again. 
It is still happening the same, both on my personal and 'team' accounts

**Comment by iriberri** [comment]
Not working hard on this yet, but took a look at the table and I saw that it has a `wkb_geometry`, so it smells to some kind of ogr2ogr conflict.

Leaving the comment here just to remember whenever I take this issue.

**Comment by iriberri** [comment]
I just confirmed, easy reproduction step:

````json
{"type": "FeatureCollection", "features": [{"type":"Feature","geometry":{"type":"Point","coordinates":[1,1]},"properties":{"cartodb_id":1,"name":null,"description":null,"wkb_geometry":"0101000020E6100000000000000000F03F000000000000F03F"}}]}
````

**Comment by iriberri** [comment]
This problem is happening with GeoJSON and CSV files:

* For KML files, ogr2ogr seems to be noticing about the `wkb_geometry` name and it does not generate a double one.
* Similar for SHP, but in this format the maximum column name is trimmed at 10 characters, so there's no collision in names
* To reproduce with CSV, try:
   ````
the_geom, wkb_geometry, lat, long

"", "", 5, 5
  ````
* For GeoJSON, ogr2ogr is generating a wkb_geometry from the feature of the GeoJSON which collides with the wkb_geometry column name in the file

**Comment by iriberri** [comment]
We're finally setting this as a won't fix. The solution is to remove the second geometric column, as two geometric columns are in principle not supported. If this need to be achieved, then rename `wkb_geometry` to something that doesn't conflict with the system.
