### ISSUE TITLE
Last fields are hidden in small screens and cannot be selected as widgets

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#7157]
In the new Editor with small screens (1st screenshot), it is impossible to select the last table fields (shot_zone_area, shot_zone_basic, team) as widgets. This behaviour does not happen with large screens (2nd screenshot).

![widgets_small_screen](https://cloud.githubusercontent.com/assets/5215798/14602327/95602464-0567-11e6-8788-92c7382d750f.png)

![widgets_large_screen](https://cloud.githubusercontent.com/assets/5215798/14602329/96c7fcbe-0567-11e6-8fa2-a825738f1e61.png)

**Comment by MariaCheca** [comment]
I noticed today the same thing is happening using Chrome in OSX:

![untitled](https://cloud.githubusercontent.com/assets/2141690/18200728/86a1d188-7106-11e6-9030-4b78cb4cfe35.gif)

**Comment by saleiva** [comment]
Interesting because this should be already fixed by @piensaenpixel

**Comment by piensaenpixel** [comment]
uhm it was fixed... i take a look

**Comment by piensaenpixel** [comment]
@MariaCheca  are you sure? it's working for me

![widgets](https://cloud.githubusercontent.com/assets/1214201/18203486/8eb9a61e-7117-11e6-8a58-b1067e0ee468.gif)

**Comment by MariaCheca** [comment]
@piensaenpixel yes, I refreshed the page in case I was missing something but it's still the same :/ It also happens in Safari and Firefox.

**Comment by piensaenpixel** [comment]
uhmm i cant reproduce it :(

**Comment by MariaCheca** [comment]
MY FAULT. I was testing in my branch which I supposed was updated enough :( Sorry @piensaenpixel, closing ✨
