### ISSUE TITLE
Intersecting data (points and polygons), error. 

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartodb#8601]
Trying to intersect TRI sites, buffered (polygons 1 km) with schools (points) in NY state, and I got the following error. 

![screen shot 2016-07-06 at 6 46 46 pm](https://cloud.githubusercontent.com/assets/2790599/16637049/2018b816-43aa-11e6-926a-03862d8df402.png)

I'm @danny on slack if any more questions.

**Comment by saleiva** [comment]
Can you try again? We fixed some stuff related with this yesterday. If it keeps happening, please reopen

**Comment by nygeog** [comment]
I'm still not getting the intersect to work. And if I try the different cardinality where Source is points it won't let the Target Layer of polygon be selected. 

![screen shot 2016-07-07 at 7 47 50 am](https://cloud.githubusercontent.com/assets/2790599/16652229/23cfe714-4417-11e6-954d-344405b63bb9.png)

**Comment by saleiva** [comment]
Can you go to the network panel, click on that request and send me the response information?
Thanks!

**Comment by nygeog** [comment]
Not totally sure if this is the info you asked for. Let me know if something else. 

![screen shot 2016-07-07 at 7 58 52 am](https://cloud.githubusercontent.com/assets/2790599/16652448/b7d8d794-4418-11e6-994f-fd94f595131f.png)

![screen shot 2016-07-07 at 7 59 04 am](https://cloud.githubusercontent.com/assets/2790599/16652449/b982eb5c-4418-11e6-92bd-8bb5278a4f44.png)

**Comment by saleiva** [comment]
perfect
thanks

**Comment by nygeog** [comment]
If its helpful, I'm also running a similar Intersect on another Map with a different set layers (NYC only instead of Statewide) and just worked.

**Comment by nygeog** [comment]
![screen shot 2016-07-07 at 8 17 50 am](https://cloud.githubusercontent.com/assets/2790599/16652862/50da8e2c-441b-11e6-9cfe-c065b4437716.png)

I tried same process minus one step (without filtering by CHEMICAL = 'LEAD'). Same error.

**Comment by nygeog** [comment]
Sanity-check, do I have the cardinality of this intersection conceptually correct (re: target, source)? 
![screen shot 2016-07-07 at 8 20 01 am](https://cloud.githubusercontent.com/assets/2790599/16652951/d2e08a2a-441b-11e6-8d54-696454449158.png)

**Comment by nygeog** [comment]
Got it to work for a subset in size and col's, I'll have someone try same steps w/ these datasets. And if that works will incrementally bring in datasets with more and more of the original data until I can identify what is going on. I'm going to close this until I figure out what the issue is. It may be data-related rather than BUILDER-related.

**Comment by nygeog** [comment]
Yeah, its now working with all the schools in the state. This may have been a **data** issue, not a **builder** issue.
